name: Deploy Application

on:
  push:
    branches:
      - main
      - feat/static-to-node-app

env:
  PROJECT_DIR: /root/project

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/the-wise:latest

    - name: Install doctl
      run: |
        curl -sL https://github.com/digitalocean/doctl/releases/download/v1.64.0/doctl-1.64.0-linux-amd64.tar.gz | tar -xzv
        sudo mv doctl /usr/local/bin

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install doctl
      run: |
        curl -sL https://github.com/digitalocean/doctl/releases/download/v1.64.0/doctl-1.64.0-linux-amd64.tar.gz | tar -xzv
        sudo mv doctl /usr/local/bin    

    - name: Validate if droplet exists
      id: check_droplet
      run: |
        doctl auth init -t ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        if doctl compute droplet list the-wise-app --format Name | grep -q the-wise-app; then
          echo "Droplet exists"
          echo "exists=true" >> $GITHUB_ENV
        else
          echo "Droplet does not exist"
          echo "exists=false" >> $GITHUB_ENV
        fi

    - name: Power on droplet if exists
      if: env.exists == 'true'
      run: |
        doctl auth init -t ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        DROPLET_ID=$(doctl compute droplet list the-wise-app --format ID --no-header)
        if [ $(doctl compute droplet get $DROPLET_ID --format Status --no-header) != "active" ]; then
          doctl compute droplet-action power-on $DROPLET_ID
          while [ $(doctl compute droplet get $DROPLET_ID --format Status --no-header) != "active" ]; do
            echo "Waiting for droplet to be active..."
            sleep 5
          done
        fi

    - name: Set up DigitalOcean droplet
      if: env.exists == 'false'
      run: |
        doctl auth init -t ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        doctl compute droplet create the-wise-app \
          --region nyc3 \
          --image docker-20-04 \
          --size s-1vcpu-1gb \
          --ssh-keys ${{ secrets.SSH_KEY_FINGERPRINT }} \
          --tag-name web \
          --wait

    - name: Wait for droplet to be ready
      run: |
        IP=$(doctl compute droplet list the-wise-app --format PublicIPv4 --no-header)
        while ! nc -z $IP 22; do
          echo "Waiting for SSH to be available..."
          sleep 5
        done

    - name: Delete old DNS records
      env:
        DO_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      run: |
        doctl auth init -t ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        records=$(doctl compute domain records list thewise.cl --no-header --format ID,Type | grep " A " | cut -d' ' -f1)
        for record in $records; do
          echo "Deleting record $record..."
          doctl compute domain records delete thewise.cl $record --force
        done
      
    - name: Create A record for thewise.cl
      env:
        DO_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      run: |
        doctl auth init -t ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        IP=$(doctl compute droplet list the-wise-app --format PublicIPv4 --no-header)
        doctl compute domain records create thewise.cl --record-type A --record-name @ --record-data $IP --record-ttl 3600
        doctl compute domain records create thewise.cl --record-type A --record-name www --record-data $IP --record-ttl 3600
  
    - name: Create project directory on Droplet
      env:
        PRIVATE_KEY: ${{ secrets.DO_SSH_PRIVATE_KEY }}
        PROJECT_DIR: ${{ env.PROJECT_DIR }}
      run: |
        IP=$(doctl compute droplet list the-wise-app --format PublicIPv4 --no-header)
        echo "$PRIVATE_KEY" > private_key
        chmod 600 private_key
        ssh -i private_key -o StrictHostKeyChecking=no root@$IP "mkdir -p $PROJECT_DIR"
        rm private_key

    - name: Copy project to Droplet
      env:
        PRIVATE_KEY: ${{ secrets.DO_SSH_PRIVATE_KEY }}
        PROJECT_DIR: ${{ env.PROJECT_DIR }}
      run: |
        IP=$(doctl compute droplet list the-wise-app --format PublicIPv4 --no-header)
        echo "$PRIVATE_KEY" > private_key
        chmod 600 private_key
        ssh -i private_key -o StrictHostKeyChecking=no root@$IP "mkdir -p $PROJECT_DIR"
        scp -i private_key -o StrictHostKeyChecking=no -r ./* root@$IP:$PROJECT_DIR
        rm private_key

    - name: Wait for DNS Propagation
      env:
        DO_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      run: |
        doctl auth init -t ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        IP=$(doctl compute droplet list the-wise-app --format PublicIPv4 --no-header)
        RETRIES=10
        DELAY=30
        for ((i=1;i<=RETRIES;i++)); do
          echo "Checking DNS propagation, attempt $i..."
          nslookup thewise.cl && nslookup www.thewise.cl && break
          echo "DNS records not found. Retrying in $DELAY seconds..."
          sleep $DELAY
        done
        if [ $i -eq $((RETRIES+1)) ]; then
          echo "DNS records did not propagate in time."
          exit 1
        fi

    - name: Install Certbot
      env:
        PRIVATE_KEY: ${{ secrets.DO_SSH_PRIVATE_KEY }}
      run: |
        IP=$(doctl compute droplet list the-wise-app --format PublicIPv4 --no-header)
        echo "$PRIVATE_KEY" > private_key
        chmod 600 private_key
        ssh -i private_key -o StrictHostKeyChecking=no root@$IP << 'EOF'
        while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do
            echo "Waiting for other process to release dpkg lock..."
            sleep 5
        done
        sudo apt-get update
        sudo apt-get install -y certbot
        EOF
        rm private_key

    - name: Validate Certbot Installation
      env:
        PRIVATE_KEY: ${{ secrets.DO_SSH_PRIVATE_KEY }}
      run: |
        IP=$(doctl compute droplet list the-wise-app --format PublicIPv4 --no-header)
        echo "$PRIVATE_KEY" > private_key
        chmod 600 private_key
        ssh -i private_key -o StrictHostKeyChecking=no root@$IP "which certbot || (echo 'Certbot not installed' && exit 1)"
        rm private_key

    - name: Check UFW rules for port 80
      env:
        PRIVATE_KEY: ${{ secrets.DO_SSH_PRIVATE_KEY }}
      run: |
        IP=$(doctl compute droplet list the-wise-app --format PublicIPv4 --no-header)
        echo "$PRIVATE_KEY" > private_key
        chmod 600 private_key
        ssh -i private_key -o StrictHostKeyChecking=no root@$IP "ufw status | grep '80/tcp' || echo 'Port 80 not allowed in UFW'"
        rm private_key
      

    - name: Install Docker Compose on Droplet
      env:
        PRIVATE_KEY: ${{ secrets.DO_SSH_PRIVATE_KEY }}
      run: |
        IP=$(doctl compute droplet list the-wise-app --format PublicIPv4 --no-header)
        echo "$PRIVATE_KEY" > private_key
        chmod 600 private_key
        ssh -i private_key -o StrictHostKeyChecking=no root@$IP << 'EOF'
        while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do
          echo "Waiting for release of dpkg lock..."
          sleep 5
        done
        apt-get update
        apt-get install -y docker-compose
        rm -rf /etc/update-motd.d/99-one-click
        EOF
        rm private_key

    - name: Create .env file on Droplet
      env:
        PRIVATE_KEY: ${{ secrets.DO_SSH_PRIVATE_KEY }}
        PROJECT_DIR: ${{ env.PROJECT_DIR }}
        PORT: ${{ secrets.PORT }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      run: |
        IP=$(doctl compute droplet list the-wise-app --format PublicIPv4 --no-header)
        echo "$PRIVATE_KEY" > private_key
        chmod 600 private_key
        ssh -i private_key -o StrictHostKeyChecking=no root@$IP << EOF
        echo "PORT=${{ secrets.PORT }}" >> $PROJECT_DIR/.env
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $PROJECT_DIR/.env
        echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> $PROJECT_DIR/.env
        echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> $PROJECT_DIR/.env
        echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> $PROJECT_DIR/.env
        EOF
        rm private_key

    - name: Check network interfaces and routes
      env:
        PRIVATE_KEY: ${{ secrets.DO_SSH_PRIVATE_KEY }}
      run: |
        IP=$(doctl compute droplet list the-wise-app --format PublicIPv4 --no-header)
        echo "$PRIVATE_KEY" > private_key
        chmod 600 private_key
        ssh -i private_key -o StrictHostKeyChecking=no root@$IP "ip addr show; ip route show"
        rm private_key
      

    - name: Check and free up port 80
      env:
        PRIVATE_KEY: ${{ secrets.DO_SSH_PRIVATE_KEY }}
      run: |
        IP=$(doctl compute droplet list the-wise-app --format PublicIPv4 --no-header)
        echo "$PRIVATE_KEY" > private_key
        chmod 600 private_key
        ssh -i private_key -o StrictHostKeyChecking=no root@$IP << 'EOF'
        if lsof -i :80 > /dev/null; then
          echo "Port 80 is in use by the following process:"
          lsof -i :80
          PID=$(lsof -t -i :80)
          echo "Killing process $PID using port 80..."
          kill -9 $PID
          echo "Process $PID has been terminated."
        else
          echo "Port 80 is not in use."
        fi
        EOF
        rm private_key

    - name: Obtain SSL Certificate with Let's Encrypt
      env:
        PRIVATE_KEY: ${{ secrets.DO_SSH_PRIVATE_KEY }}
        EMAIL: ${{ secrets.LETS_ENCRYPT_EMAIL }}
      run: |
        IP=$(doctl compute droplet list the-wise-app --format PublicIPv4 --no-header)
        echo "$PRIVATE_KEY" > private_key
        chmod 600 private_key
        RETRIES=5
        DELAY=30
        for ((i=1;i<=RETRIES;i++)); do
          echo "Attempt $i to obtain SSL certificate..."
          ssh -i private_key -o StrictHostKeyChecking=no root@$IP <<EOF
          certbot certonly --standalone -d thewise.cl -d www.thewise.cl --non-interactive --agree-tos -m $EMAIL || cat /var/log/letsencrypt/letsencrypt.log 
        EOF
          if [ $? -eq 0 ]; then
            echo "SSL certificate obtained successfully."
            break
          else
            echo "Failed to obtain SSL certificate. Retrying in $DELAY seconds..."
            sleep $DELAY
          fi
        done
        if [ $i -eq $((RETRIES+1)) ]; then
          echo "Failed to obtain SSL certificate after multiple attempts."
          exit 1
        fi
        rm private_key

    - name: Deploy application
      env:
        PRIVATE_KEY: ${{ secrets.DO_SSH_PRIVATE_KEY }}
        PROJECT_DIR: ${{ env.PROJECT_DIR }}
      run: |
        IP=$(doctl compute droplet list the-wise-app --format PublicIPv4 --no-header)
        echo "$PRIVATE_KEY" > private_key
        chmod 600 private_key
        ssh -i private_key -o StrictHostKeyChecking=no root@$IP << 'EOF'
        while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do
          echo "Waiting for release of dpkg lock..."
          sleep 5
        done
        apt-get update
        apt-get install -y docker-compose
        cd /root/project/
        pwd
        ls
        docker-compose up -d
        EOF
        rm private_key

    - name: Validate SSL Certificate
      env:
        PRIVATE_KEY: ${{ secrets.DO_SSH_PRIVATE_KEY }}
      run: |
        IP=$(doctl compute droplet list the-wise-app --format PublicIPv4 --no-header)
        echo "$PRIVATE_KEY" > private_key
        chmod 600 private_key
        ssh -i private_key -o StrictHostKeyChecking=no root@$IP << 'EOF'
        if [ ! -f /etc/letsencrypt/live/thewise.cl/fullchain.pem ]; then
          echo "SSL Certificate not found"; exit 1
        fi
        EOF
        rm private_key