name: Deploy to DigitalOcean
on:
  push:
    branches:
      - main
      - feat/static-to-node-app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/the-wise:latest

    - name: Deploy to DigitalOcean
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Set up DigitalOcean droplet
      run: |
        doctl auth init -t ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        doctl compute droplet create the-wise-app \
          --region nyc3 \
          --image docker-20-04 \
          --size s-1vcpu-1gb \
          --ssh-keys ${{ secrets.SSH_KEY_FINGERPRINT }} \
          --tag-name web \
          --wait

    - name: Wait for droplet to be ready
      run: |
        IP=$(doctl compute droplet list the-wise-app --format PublicIPv4 --no-header)
        while ! nc -z $IP 22; do
          echo "Waiting for SSH to be available..."
          sleep 5
        done

    - name: Deploy application
      run: |
        ssh -o StrictHostKeyChecking=no root@$(doctl compute droplet list the-wise-app --format PublicIPv4 --no-header) << 'EOF'
        docker pull ${{ secrets.DOCKER_USERNAME }}/the-wise:latest
        docker stop the-wise || true
        docker rm the-wise || true
        docker run -d --name the-wise -p ${{ secrets.PORT }}:${{ secrets.PORT }} ${{ secrets.DOCKER_USERNAME }}/the-wise:latest
        EOF
