name: Provision Infrastructure

on:
  push:
    branches:
      - main
      - feat/static-to-node-app

jobs:
  provision:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
    - name: Initialize Terraform
      run: |
        cd infra
        terraform init

    - name: Apply Terraform configurations
      env:
        DO_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        SSH_FINGERPRINT: ${{ secrets.SSH_KEY_FINGERPRINT }}
        DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/the-wise:latest
        PORT: ${{ secrets.PORT }}
        PRIVATE_KEY: ${{ secrets.DO_SSH_PRIVATE_KEY }}
      run: |
        cd infra
        terraform apply \
          -var "do_token=${DO_TOKEN}" \
          -var "ssh_fingerprint=${SSH_FINGERPRINT}" \
          -var "docker_image=${DOCKER_IMAGE}" \
          -var "port=${PORT}" \
          -var "private_key=${PRIVATE_KEY}" \
          -auto-approve