name: Provision Infrastructure
#name: Provision Infrastructure
#
#
#on:
#on:
#  push:
#  push:
#    branches:
#    branches:
#      - main
#      - main
#      - feat/static-to-node-app
#      - feat/static-to-node-app
#
#
#jobs:
#jobs:
#  provision:
#  provision:
#    runs-on: ubuntu-latest
#    runs-on: ubuntu-latest
#
#
#    steps:
#    steps:
#    - name: Checkout code
#    - name: Checkout code
#      uses: actions/checkout@v2
#      uses: actions/checkout@v2
#
#
#    - name: Install Terraform
#    - name: Install Terraform
#      uses: hashicorp/setup-terraform@v1
#      uses: hashicorp/setup-terraform@v1
#      with:
#      with:
#        terraform_version: 1.0.0
#        terraform_version: 1.0.0
#
#
#    - name: Configure AWS credentials
#    - name: Configure AWS credentials
#      uses: aws-actions/configure-aws-credentials@v1
#      uses: aws-actions/configure-aws-credentials@v1
#      with:
#      with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
#          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
#    - name: Initialize Terraform
#    - name: Initialize Terraform
#      run: |
#      run: |
#        cd infra
#        cd infra
#        terraform init
#        terraform init
#
#
#    - name: Apply Terraform configurations
#    - name: Apply Terraform configurations
#      env:
#      env:
#        DO_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
#        DO_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
#        SSH_FINGERPRINT: ${{ secrets.SSH_KEY_FINGERPRINT }}
#        SSH_FINGERPRINT: ${{ secrets.SSH_KEY_FINGERPRINT }}
#        DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/the-wise:latest
#        DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/the-wise:latest
#        PORT: ${{ secrets.PORT }}
#        PORT: ${{ secrets.PORT }}
#        PRIVATE_KEY: ${{ secrets.DO_SSH_PRIVATE_KEY }}
#        PRIVATE_KEY: ${{ secrets.DO_SSH_PRIVATE_KEY }}
#      run: |
#      run: |
#        cd infra
#        cd infra
#        terraform apply \
#        terraform apply \
#          -var "do_token=${DO_TOKEN}" \
#          -var "do_token=${DO_TOKEN}" \
#          -var "ssh_fingerprint=${SSH_FINGERPRINT}" \
#          -var "ssh_fingerprint=${SSH_FINGERPRINT}" \
#          -var "docker_image=${DOCKER_IMAGE}" \
#          -var "docker_image=${DOCKER_IMAGE}" \
#          -var "port=${PORT}" \
#          -var "port=${PORT}" \
#          -var "private_key=${PRIVATE_KEY}" \
#          -var "private_key=${PRIVATE_KEY}" \
#          -auto-approve
#          -auto-approve